import React from 'react';
import { Link } from 'react-router-dom';
import { Scale, ChevronLeft, CheckCircle } from 'lucide-react';
import { Button } from '../components/ui/button';

const Terms = () => {
  return (
    <div className="min-h-screen bg-[#0c0a1a] text-gray-300 py-24 px-6 relative overflow-hidden">
      {/* Decorative blobs */}
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-violet-600/5 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-blue-600/5 rounded-full blur-[100px] pointer-events-none" />

      <div className="max-w-4xl mx-auto relative z-10">
        <Link to="/" className="inline-flex items-center gap-2 text-violet-400 hover:text-violet-300 mb-12 transition-colors">
          <ChevronLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <div className="flex items-center gap-4 mb-8">
          <div className="w-12 h-12 rounded-2xl bg-violet-500/10 border border-violet-500/20 flex items-center justify-center">
            <Scale className="w-6 h-6 text-violet-400" />
          </div>
          <div>
            <h1 className="text-4xl font-bold text-white tracking-tight">Terms of Service</h1>
            <p className="text-gray-500">Last updated: April 27, 2026</p>
          </div>
        </div>

        <div className="prose prose-invert prose-violet max-w-none space-y-12 text-gray-400 leading-relaxed">
          <section>
            <div className="flex items-center gap-3 mb-4">
              <CheckCircle className="w-5 h-5 text-violet-400" />
              <h2 className="text-2xl font-semibold text-white m-0">Agreement to Terms</h2>
            </div>
            <p>
              By accessing and using Nexa.AI, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">Use License</h2>
            <p>
              Permission is granted to temporarily use Nexa.AI for personal, non-commercial, or commercial website generation in accordance with your subscription plan. This is the grant of a license, not a transfer of title.
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-4">
              <li>You may not use the service for any illegal or unauthorized purpose.</li>
              <li>You must not transmit any worms or viruses or any code of a destructive nature.</li>
              <li>You are responsible for the websites you generate and publish using our tool.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">Accounts and Payments</h2>
            <p>
              When you create an account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure.
            </p>
            <p className="mt-4">
              Payments are processed securely via Razorpay. Subscriptions are billed in advance on a recurring basis. All fees are non-refundable except as required by law.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">Intellectual Property</h2>
            <p>
              The code and designs generated by Nexa.AI for you are your property to use. However, the core Nexa.AI engine, UI components, branding, and proprietary algorithms remain the exclusive property of Nexa.AI and its licensors.
            </p>
          </section>

          <section className="border-t border-white/10 pt-12 text-center">
            <h2 className="text-2xl font-semibold text-white mb-4">Questions?</h2>
            <p className="mb-8">If you have any questions about these Terms, please contact us.</p>
            <Button className="bg-white/10 hover:bg-white/15 text-white rounded-full px-8 border border-white/10">
              Contact Support
            </Button>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;
